### ISSUE TITLE
Corregir Menu Formulación - Etapas de Pre Inversion

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#110]
![Screen Shot 2017-12-21 at 7:41 PM](http://marker.screenshots.prod.s3.amazonaws.com/40919c19ff05461aada6a2b901fb925b-1513885311165.png)

No se esta mostrando correctamente el menú, arreglar los estilos para mostrarlo de manera correcta.

---
### More Info

**Source URL**: [http://192.168.1.34/SMP/index.php/FEformulacion/Feformulacion/all](http://192.168.1.34/SMP/index.php/FEformulacion/Feformulacion/all)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34359271-7f439d8e-ea24-11e7-8917-fef3bd523461.png)
![image](https://user-images.githubusercontent.com/1704345/34359279-943ec538-ea24-11e7-8427-ae9125aec1a9.png)
