### ISSUE TITLE
Corregir Responsable del Entregable - Entregable del estudio

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#116]
![Screen Shot 2017-12-21 at 9:22 PM](http://marker.screenshots.prod.s3.amazonaws.com/ce09bc38810d4d2a880b1c6c133dfd86-1513891334629.png)

- Corregir la caja de texto de buscar esta descuadra con el grid
- No se esta notando quien es la persona seleccionada al momento de agregarla.

---
### More Info

**Source URL**: [http://192.168.1.34/SMP/index.php/FEentregableEstudio/ver_FEentregable/1141](http://192.168.1.34/SMP/index.php/FEentregableEstudio/ver_FEentregable/1141)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by florescobar919** [comment]
al seleccionar una persona se cambia de color la fila.. y ase agreago div responsivo en la tabla
