### ISSUE TITLE
Actualizar mensaje de Ejecución de Inversiones unidad de Medida Tiempo

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#130]
![image](https://user-images.githubusercontent.com/33671407/34301639-54d835f4-e6fb-11e7-83bf-75c651242eab.png)

Al mostrar el indicador , Tiempo de Ejecución se muestra una cantidad "19" actualizar mensaje correcto en que unidad de medida tiempo al que representa.

**Comment by joelmez4** [comment]
@RubenRazuri  indicar la ruta del Issue

**Comment by joelmez4** [comment]
http://smptracing.ddns.net/Expediente_Tecnico/ReporteEstadistico?id_et=90
