### ISSUE TITLE
Actualizar mensajes Tooltip en los botones que contienen abreviaturas

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#138]
![image](https://user-images.githubusercontent.com/33671407/34302627-bb9d1e86-e6ff-11e7-826c-5d584c47a753.png)

En Ejecución , operaciones, dentro de componentes, metas y partidas, se muestran los Registros de componentes, metas y partidas,  los botones que contienen abreviaturas, mostrar mensaje de su función o contenido.

**Comment by joelmez4** [comment]
Agregar la ruta de issue @RubenRazuri

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34305330-a48f406e-e70b-11e7-86e6-521e7bf4241f.png)
