### ISSUE TITLE
Mostrar los dos tipos de Mantenimientos de parámetros.

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#141]
![Screen Shot 2017-12-26 at 1:48 PM](http://marker.screenshots.prod.s3.amazonaws.com/04e208724b044097a8b599bf723fd2c5-1514296127172.png)

Mostrar en el Menú el los nombres de los campos de un mismo mantenimiento de parámetro, para ser mas fácil su ubicación  Sector Entidad

---
### More Info

**Source URL**: [http://192.168.1.36/SMP/index.php/Sector](http://192.168.1.36/SMP/index.php/Sector)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by florescobar919** [comment]
corregido
