### ISSUE TITLE
Error de carga en la creación de Nueva unidad de Medida

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#154]
![Screen Shot 2017-12-26 at 4:29 PM](http://marker.screenshots.prod.s3.amazonaws.com/1bbe6269400f4884b58ded3364f68361-1514305779139.png)
---
### More Info

**Source URL**: [http://192.168.1.36/SMP/index.php/Unidad_Medida](http://192.168.1.36/SMP/index.php/Unidad_Medida)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.800000011920929x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by florescobar919** [comment]
no se le asigno esta opcion al usuario..

**Comment by RubenRazuri** [comment]
El Usuario Admin tiene control total, verificar
