### ISSUE TITLE
No se cumple con los tipos de Usuario planificado

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#156]
![image](https://user-images.githubusercontent.com/33671407/34361641-ef824a36-ea39-11e7-85ed-68a9d050d5fb.png)

Se planteo trabajar en base a tres tipos de Usuario 
N° | Tipo Usuario
1 | Administrador
2 | Actualizador
3 | Consultor

http://192.168.1.36/SMP/index.php/Usuario

**Comment by joelmez4** [comment]
@RubenRazuri consultar con @mrlivano

**Comment by RubenRazuri** [comment]
Se mantendrá como lo planificado y a los usuarios se los agrupa de acuerdo a su nivel

**Comment by mrlivano** [comment]
La configuración de tipos de usuarios se hace en base de datos en la tabla USUARIO_TIPO
