### ISSUE TITLE
Validar pase de Proyecto de Formulacion a Ejecucion

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#161]
![Screen Shot 2017-12-27 at 5:21 PM](http://marker.screenshots.prod.s3.amazonaws.com/757895048f6942e8a771b7ea79df49db-1514395318404.png)

- Validar mediante un parametro en este caso un documento o resolucion. Consultarlo con Analista de Negocio

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/FEformulacion/Feformulacion/all](http://192.168.88.89/SMP/index.php/FEformulacion/Feformulacion/all)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by florescobar919** [comment]
por favor, ser mas especifico
