### ISSUE TITLE
Validar numero de caracteres Programacion PMI

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#167]
![Screen Shot 2017-12-27 at 7:58 PM](http://marker.screenshots.prod.s3.amazonaws.com/bccf67262d1749579ec891e51b905cc4-1514404726431.png)

- Validar el numero de caracteres para cada campo que no exceda lo permitido y que no haga overflow con el numero de  caracteres en la base de datos. 

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/ProyectoInversion](http://192.168.88.89/SMP/index.php/ProyectoInversion)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
atendido
