### ISSUE TITLE
Corregir boton eliminar Mantenimiento - Grupo Funcional

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#173]
![Screen Shot 2017-12-27 at 8:22 PM](http://marker.screenshots.prod.s3.amazonaws.com/60a33794d2fd41eda0e0bfd2fc91b048-1514406126319.png)

- El boton eliminar no esta realizando ninguna funcionalidad, deberia mostrar una ventana de confirmacion antes de eliminar el registro.

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/CadenaFuncional](http://192.168.88.89/SMP/index.php/CadenaFuncional)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34422196-fb358448-ebe1-11e7-92cb-84a2a8cf9edc.png)
