### ISSUE TITLE
Corregir formulario informacion Programa presupuestal

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#183]
![Screen Shot 2017-12-27 at 8:38 PM](http://marker.screenshots.prod.s3.amazonaws.com/1fe70514a37947bfbe469bb3eae21d10-1514407094895.png)

- Estandarizar el boton por CERRAR
- La funcionalidad del boton eliminar no esta funcionando correctamente

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/InformacionPresupuestal](http://192.168.88.89/SMP/index.php/InformacionPresupuestal)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34422533-14f090ec-ebe4-11e7-86b3-26c344dcee4d.png)
