### ISSUE TITLE
Corregir formulario Registrar meta presupuestal

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#186]
![Screen Shot 2017-12-27 at 8:51 PM](http://marker.screenshots.prod.s3.amazonaws.com/ec63bb38463e45f9919830edc31488b3-1514407868385.png)

- Verificar el campo ID con un numero que se observa al modificar
- El boton guardar no esta funcionando correctamente
- Estandarizar el boton CERRAR

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/MetaPresupuestal](http://192.168.88.89/SMP/index.php/MetaPresupuestal)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
correccion de meta presupuestal
