### ISSUE TITLE
Verificar Grafico PMI

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#189]
![Screen Shot 2017-12-27 at 9:08 PM](http://marker.screenshots.prod.s3.amazonaws.com/a69dc51c5f1d4596a976ddf6a2c3e9db-1514408917188.png)

Verificar porque el grafico carga en algunas computadoras y en otras no.

---
### More Info

**Source URL**: [http://192.168.88.89/SMP/index.php/PrincipalPmi/pmi](http://192.168.88.89/SMP/index.php/PrincipalPmi/pmi)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34422224-35d0450c-ebe2-11e7-8539-77b6f6c5745a.png)

Si carga
