### ISSUE TITLE
Actualizar el combo Grupo

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#21]
![Screen Shot 2017-11-24 at 9:03 PM](http://marker.screenshots.prod.s3.amazonaws.com/7e259872ea514eb2baf75c9b17b61dbf-1511557434814.png)
---
### More Info

**Source URL**: [http://smptracing.ddns.net/bancoproyectos/](http://smptracing.ddns.net/bancoproyectos/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by RubenRazuri** [comment]
Al crear un proyecto Idea, de acuerdo a su naturaleza, nivel de gobierno, Unidad Ejecutora, Función División, el combo “Grupo” no actualiza (no muestra alternativa para seleccionar) es un requisito.

**Comment by joelmez4** [comment]
Falta ingresar datos de acuerdo al siguiente documento https://www.mef.gob.pe/contenidos/archivos-descarga/anexo07_directiva001_2017EF6301.pdf

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33737790-5a5e8ee8-db65-11e7-9e8a-cfa3a218ca8a.png)
