### ISSUE TITLE
Actualizar controles TextBox

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#24]
![Screen Shot 2017-11-27 at 11:01 AM](http://marker.screenshots.prod.s3.amazonaws.com/a2153953098445dcb974b2b97fffe663-1511780512908.png)

**Summary:** 
Actualizacion de Textbox
**Steps to Reproduce:** 
Agregar la información desde la base de datos
**Expected Results:** 
Información sin posibilidad de cambio
**Actual Results:** 

**Notes:**

---
### More Info

**Source URL**: [http://smptracing.ddns.net/MetaPip/meta_pip](http://smptracing.ddns.net/MetaPip/meta_pip)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.800000011920929x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
debe de ser llenado manualmente
