### ISSUE TITLE
Validación de rutas de archivo 

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#29]
![Screen Shot 2017-11-27 at 6:03 PM](http://marker.screenshots.prod.s3.amazonaws.com/0691cf9140914f10832d6761b04cd249-1511805836523.png)

Al agregar un archivo, el sistema permite ingresar a la información de los módulos borrando el nombre del archivo adjunto. 
Bloquear esta ruta de acceso

---
### More Info

**Source URL**: [http://smptracing.ddns.net/uploads/](http://smptracing.ddns.net/uploads/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34013984-914be0d6-e0e7-11e7-8576-86db8ce9a0a6.png)
