### ISSUE TITLE
Creación de Perfiles para cada usuario del sistema

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#32]
![Screen Shot 2017-12-05 at 2:40 PM](http://marker.screenshots.prod.s3.amazonaws.com/d253bd7ee2094684946d10df5dd1d5e7-1512484836193.png)

Según el documento solicitado crear los perfiles con los accesos y permisos correspondientes para cada usuario final del sistema.

---
### More Info

**Source URL**: [http://localhost/smp/Usuario](http://localhost/smp/Usuario)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33618620-0a9d0354-d9b1-11e7-9f73-14c008a33ccd.png)
