### ISSUE TITLE
Validar numero de caracteres PMI NO PIP

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#37]
![Screen Shot 2017-12-05 at 5:27 PM](http://marker.screenshots.prod.s3.amazonaws.com/979821f534ab4a5ebe5ffd647ee6e1b7-1512494830045.png)

Al momento de ingresar un mayor numero de caracteres esta dando  error de base de datos en el momento de la inserción.

---
### More Info

**Source URL**: [http://192.168.1.87/smp/bancoproyectos/NoPip](http://192.168.1.87/smp/bancoproyectos/NoPip)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33834381-c44dad78-de50-11e7-866e-7acd391c7bf0.png)
