### ISSUE TITLE
Error en la carga de controles del menú 

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#40]
![Screen Shot 2017-12-06 at 4:31 PM](http://marker.screenshots.prod.s3.amazonaws.com/90cebb07722a4682859e3978ee5e57fb-1512577917717.png)
---
### More Info

**Source URL**: [http://200.37.200.182/FEentregableEstudio/ver_FEentregable/1140](http://200.37.200.182/FEentregableEstudio/ver_FEentregable/1140)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.8999999761581421x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>
Error en el modulo de controles de carga, en la opción Principal submenú Formulación, opción entregable.

**Comment by joelmez4** [comment]
especificar procedimiento al ingresar a esta interfaz

**Comment by nyxjoel** [comment]
![image](https://user-images.githubusercontent.com/1704345/33681824-b0dcbcae-da93-11e7-843a-fb04c887c77a.png)

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33681925-eed1de86-da93-11e7-9850-b047de370977.png)
