### ISSUE TITLE
Validar asteriscos para campos obligatorios en Cartera PMI

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#44]
![Screen Shot 2017-12-06 at 10:06 PM](http://marker.screenshots.prod.s3.amazonaws.com/6ab5ca8fa51c4f0fbbcaa30edb5ee9a8-1512597967299.png)

Solo los campos obligatorios deben llevar asterisco

---
### More Info

**Source URL**: [http://192.168.1.34/smp/CarteraInversion](http://192.168.1.34/smp/CarteraInversion)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
2 *
