### ISSUE TITLE
Corregir modulo Pro Inversiones PMI

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#45]
![Screen Shot 2017-12-06 at 10:15 PM](http://marker.screenshots.prod.s3.amazonaws.com/476e907535364a5c9ed0f67fe717d230-1512598556719.png)

- Agregar indivualmente la programación para cada año
- Validar que no se puedan agregar mas años si sobrepasan el monto total

---
### More Info

**Source URL**: [http://192.168.1.34/smp/programar_pip](http://192.168.1.34/smp/programar_pip)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
el procedimiento de programación es para tres años según norma
