### ISSUE TITLE
Nombre correcto a la cabecera 

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#48]
![Screen Shot 2017-12-06 at 10:31 PM](http://marker.screenshots.prod.s3.amazonaws.com/2eb2821a8e6b468892fd39b35128a357-1512599504578.png)

Si va a realizar  un ingreso de datos proyectado a 3 años debe indicar la cabecera ,  ejemplo "Proyección de Gastos".

---
### More Info

**Source URL**: [http://200.37.200.182/index.php/programar_pip](http://200.37.200.182/index.php/programar_pip)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>75%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.75x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
Nombre correcto a la cabecera #48
