### ISSUE TITLE
Corregir tooltip Criterios de Priorizacion

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#52]
![Screen Shot 2017-12-06 at 10:43 PM](http://marker.screenshots.prod.s3.amazonaws.com/0f87ff11a673457d8f3ae313395d87bd-1512600178513.png)

Describir en tooltips la funcionalidad  de los botones

---
### More Info

**Source URL**: [http://192.168.1.34/smp/PmiCriterioG/criterioFuncion/2018](http://192.168.1.34/smp/PmiCriterioG/criterioFuncion/2018)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33737092-f6479136-db62-11e7-9c51-fbbf46fa9d6b.png)
