### ISSUE TITLE
Corregir Grid en Principal > Formulacion

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#53]
![Screen Shot 2017-12-07 at 8:55 PM](http://marker.screenshots.prod.s3.amazonaws.com/3e389001492343d18d85f78ef9719eaf-1512680146368.png)

La tabla esta saliendose del Grid

---
### More Info

**Source URL**: [http://192.168.1.34/smp/FEformulacion/Feformulacion/all](http://192.168.1.34/smp/FEformulacion/Feformulacion/all)

<table><tr><td><strong>Browser</strong></td><td>Chrome 62.0.3202.94</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/33741818-e3d0f662-db73-11e7-90d5-8af23511a8d7.png)

**Comment by nyxjoel** [comment]
![image](https://user-images.githubusercontent.com/1704345/33741818-e3d0f662-db73-11e7-90d5-8af23511a8d7.png)
