### ISSUE TITLE
Actualizar las cabeceras de operación y mantenimiento en PMI

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#56]
![Screen Shot 2017-12-12 at 5:09 PM](http://marker.screenshots.prod.s3.amazonaws.com/b51d4ef3984444a18bbefcce6e39c5c4-1513098593152.png)

**Summary:** 
La operación que se agregó esta con distintas cabeceras, de las que se agregaron 
**Expected Results:** 
Corregir los nombres de cada cabecera 

---
### More Info

**Source URL**: [http://192.168.1.100/index.php/bancoproyectos/NoPip](http://192.168.1.100/index.php/bancoproyectos/NoPip)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.84</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>80%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.800000011920929x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
#56 Se actualizó las cabeceras de operación y mantenimiento en PMI y titulos de modales
