### ISSUE TITLE
Corregir Mensaje de Opciones en Formulación 

### ISSUE THREAD

**Issue by RubenRazuri** [smptracing/SMP#57]
![Screen Shot 2017-12-14 at 4:52 PM](http://marker.screenshots.prod.s3.amazonaws.com/beeb3ac0ad3d458a981540a32537c3fd-1513270331080.png)
---
### More Info

**Source URL**: [http://200.37.200.182/FEformulacion/Feformulacion/all](http://200.37.200.182/FEformulacion/Feformulacion/all)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.84</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows Server 2008 R2 / 7 7</td></tr><tr><td><strong>Viewport Size</strong></td><td>1384 x 746</td></tr><tr><td><strong>Zoom Level</strong></td><td>75%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.75x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36</td></tr></table>

**Comment by jeus1609** [comment]
Corregido

**Comment by jeus1609** [comment]
Asignar a Programador front-end
