### ISSUE TITLE
Estandarizar botones "Cerrar"

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#64]
![Screen Shot 2017-12-18 at 1:39 PM](http://marker.screenshots.prod.s3.amazonaws.com/82b3e71dd56641b8aed0505914f46704-1513604341265.png)

El nombre de los botones en todas las pantallas debe ser con el nombre: "Cerrar", para que no esten diferentes.

---
### More Info

**Source URL**: [http://192.168.1.40/SMP/index.php/bancoproyectos](http://192.168.1.40/SMP/index.php/bancoproyectos)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.84</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36</td></tr></table>

**Comment by mrlivano** [comment]
#64 corregido en pmi
