### ISSUE TITLE
Corregir Ver Etapa en Formulacion PIP

### ISSUE THREAD

**Issue by Flexcash** [smptracing/SMP#90]
![Screen Shot 2017-12-19 at 4:20 PM](http://marker.screenshots.prod.s3.amazonaws.com/b2830e13f0674903a3f37c93b1cbb955-1513700455820.png)

- Remover los controles de la parte superior.
- Traducir el Complete a Completado
- Verificar el link que aparece al inicio del registro

---
### More Info

**Source URL**: [http://192.168.1.34/SMP/EvaluacionFE/FeEvaluacion?id_est_inv=245](http://192.168.1.34/SMP/EvaluacionFE/FeEvaluacion?id_est_inv=245)

<table><tr><td><strong>Browser</strong></td><td>Chrome 63.0.3239.108</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10</td></tr><tr><td><strong>Viewport Size</strong></td><td>1382 x 784</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>User Agent</strong></td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36</td></tr></table>

**Comment by joelmez4** [comment]
![image](https://user-images.githubusercontent.com/1704345/34221460-18f18516-e586-11e7-9894-34825f841631.png)
